services:
  mysql:
    image: mysql:8.0
    container_name: textile_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test:
        ['CMD-SHELL', 'mysqladmin ping -h localhost -uroot -p"$${MYSQL_ROOT_PASSWORD}"']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: astrid_quality_app
    restart: unless-stopped
    ports:
      - '5000:5000'
    environment:
      SECRET_KEY: '${SECRET_KEY}'

      MYSQL_HOST: mysql
      MYSQL_PORT: '3306'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'

      CAMERA_INDEX: '${CAMERA_INDEX}'
      CAMERA_IP: '${CAMERA_IP}'
      CAMERA_USER: '${CAMERA_USER}'
      CAMERA_PASSWORD: '${CAMERA_PASSWORD}'
      CAMERA_RTSP_PORT: '${CAMERA_RTSP_PORT}'
      CAMERA_CHANNEL: '${CAMERA_CHANNEL}'
      CAMERA_SUBTYPE: '${CAMERA_SUBTYPE}'
      CAMERA_WIDTH: '${CAMERA_WIDTH}'
      CAMERA_HEIGHT: '${CAMERA_HEIGHT}'
      CAMERA_FPS: '${CAMERA_FPS}'

      ROI_X1: '${ROI_X1}'
      ROI_Y1: '${ROI_Y1}'
      ROI_X2: '${ROI_X2}'
      ROI_Y2: '${ROI_Y2}'
      PATCHCORE_CKPT: '/app/patchcore_results/Patchcore/BLUSA_002_S_ROSA_FRONT/v1/weights/lightning/model.ckpt'
      PATCHCORE_PIXEL_THRESHOLD: '${PATCHCORE_PIXEL_THRESHOLD}'
      PATCHCORE_MAX_BOX_RATIO: '${PATCHCORE_MAX_BOX_RATIO}'

    volumes:
      - ./static/captures:/app/static/captures
      - ./static/results:/app/static/results
      - ./models:/app/models
      - ./patchcore_results:/app/patchcore_results:ro

    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
